name: ESLint

on:
  - pull_request

jobs:
  eslint:
    env:
      working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
        working_directory: ${{env.working_directory}}
      - name: Run ESLint
        run: npm run lint
        working_directory: ${{env.working_directory}}
